server:
  port: 8088
#数据库
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.18.128:3306/test?characterEncoding=UTF8
    username: root
    password: 1903@heBut.
mybatis:
  mapper-locations: classpath:dao/*
  xml: dao/*.xml


